[book]
title = "The Rust Programming Language"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"
language = "en"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang/book"

[language.en]
name = "English"

[language.ja]
name = "日本語"
title = "The Rust Programming Language 日本語版"

[language.fr]
name = "Français"
title = "Le langage de programmation Rust"
author = "Steve Klabnik et Carol Nichols, avec la participation de la Communauté Rust"
